__default__:
  partition: Lewis,hpc5,General
  time: 0-02:00
  mem: 1G
  cpus: 1
FastqDump:
  time: 0-12:00
  mem: 60G
  job-name: FastqDump
  output: reports/FastqDump-%j.slurm.out
FastQC:
  time: 0-01:00
  mem: 10G
  job-name: FastQC
  output: reports/FastQC-%j.slurm.out
Trimmomatic:
  time: 0-04:00
  mem: 10G
  job-name: Trimmomatic
  output: reports/Trimmomatic-%j.slurm.out
BWA:
  time: 0-12:00
  mem: 100G
  job-name: BWA
  output: reports/BWA-%j.slurm.out
